Cray-HPE/docs-uan

.github/workflows/build_uan_docs.yaml

- Fixes casmuser-2930
This PR enables HTML docs to be built on a push to the main branch. 
Low risk.

Automate docs build on main branch push

---

docs/portal/developer-portal/operations/Configure_Interfaces_on_UANs.md

This PR updates the documentation for supporting bonded NMN interfaces and also updates the way bonded interfaces for CAN are defined.
Fixes [CASMUSER-2677](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-2677)
Fixes [CASMUSER-2900](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-2900)
Merge after https://github.com/Cray-HPE/uan/pull/62 which is the code change PR.

casmuser-2677: Update Configure Interfaces on UANs for NMN bonding

---

docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md

This PR adds the procedure for setting the UAN root password to the docs.  It also adds some notes about COS layers that are required for UAN CFS configuration.

Add setting UAN password steps to docs

---

docs/portal/developer-portal/operations/Configure_Interfaces_on_UANs.md
docs/portal/developer-portal/operations/UAN_Ansible_Roles.md

This PR updates the UAN_Ansible_Roles.md file to include the new variables supporting bonded NMN and the new way CAN slaves are defined.  It also clarifies some of the wording around CAN and bonded NMN in Configure_Interfaces_on_UANs.md.

casmuser-2677: Add Ansible roles changes for NMN bonding

---

docs/portal/developer-portal/hugo_toc.json
docs/portal/developer-portal/operations/Configure_Interfaces_on_UANs.md
docs/portal/developer-portal/operations/UAN_Ansible_Roles.md
docs/portal/developer-portal/uan_admin.ditamap
docs/portal/developer-portal/uan_install.ditamap
docs/portal/developer-portal/upgrade/Notable_Changes.md

This PR contains changes to UAN docs for the UAN 2.5.9 release which adds support for NMN bonding.
With this change the proper hugo_toc.json for the release is added for Hugo doc builds.

Casmuser 3181 2.5: Bonded UAN for UAN-2.5.9

---

docs/portal/developer-portal/build.sh
docs/portal/developer-portal/flatten.sh

- Fixes CASMUSER-3055
- Docs portal Bugfix Pull Request
This flattens the directory structure (and updates links in the Markdown files) of the source files used by DITA-OT to build the HTML5 and JSON bundle that gets uploaded to HPESC. Only the HPESC bundle build path is affected by this.
This is a docs tooling-only change.
Very low risk to the Hugo build process or to the process that builds the PDF/HTML tarball. 
**NOTE** From now on we must avoid having two Markdown files with the exact same file name.
We need a follow-up PR that replaces cross-references of this type: `[Link Text](MARKDOWN_FILE_NAME.md#SUBSECTION)`
with links of this type: `[Link Text](MARKDOWN_FILE_NAME.md)` if we want those cross-references to work in the PDF generated by the portal from the HTML.

Casmuser 3055

---

docs/hugo/docs-uan/bin/lib/content_prep
docs/portal/developer-portal/hugo_toc.json

This PR fixes some errors found in title generation from the markdown files and generation of the sidebar ordering which is based on the hugo doc front matter inserted in each index.md file.
index.md files were being generated with every word in the title being capitalized and acronym capitalization not being restricted to word boundaries which resulted in words like "(Technical Preview) being rendered as (techNICal Preview)".
There was also a case where an errant "\r" character in a markdown file resulted in that title not being matched and then not being weighted properly for sidebar ordering in hugo.

fix title generation

---

docs/portal/developer-portal/advanced/Enabling_K3s.md
docs/portal/developer-portal/installation_prereqs/Configure_the_BIOS_of_an_HPE_UAN.md
docs/portal/developer-portal/installation_prereqs/Configure_the_BMC_for_UANs_with_iLO.md
docs/portal/developer-portal/installation_prereqs/Prepare_for_UAN_Product_Installation.md
docs/portal/developer-portal/operations/About_UAN_Configuration.md
docs/portal/developer-portal/operations/Build_a_New_UAN_Image_Using_the_COS_Recipe.md
docs/portal/developer-portal/operations/Create_UAN_Boot_Images.md
docs/portal/developer-portal/troubleshooting/Troubleshoot_UAN_Boot_Issues.md

- Fixes CASMUSER-3187
**IMPORTANT** From now on, avoid using cross references of the form `[LINK TEXT](TARGET_FILE.md#TARGET_SECTION_WITHIN_TARGET_FILE)` . Use `[LINK TEXT](TARGET_FILE.md)` instead. In the rare cases we need to get more specific, we can break up the file into separate ones and point to one of the new, smaller files.
In all the cases I fixed, the `#TARGET_SECTION_WITHIN_TARGET_FILE` was just the name of the Level 1 header anyway, so it had the same effect as just referencing the TARGET_FILE.
Fixes nearly all broken cross-references in the guide PDFs generated by HPESC. One known exception: the "Create UAN Boot Images" procedure still contains a broken link to "Build a New UAN Image Using a COS Recipe". I'm so far unable to determine why.
The "fix" is …

changed xref targets to be the whole file, not the first section.

---

docs/portal/developer-portal/hugo_toc.json
docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md
docs/portal/developer-portal/operations/Basic_UAN_Configuration.md
docs/portal/developer-portal/operations/Create_UAN_Boot_Images.md
docs/portal/developer-portal/troubleshooting/Troubleshoot_UAN_CFS_and_Network_Configuration_Issues.md
docs/portal/developer-portal/troubleshooting/Troubleshoot_UAN_Disk_Configuration_Issues.md
docs/portal/developer-portal/uan_admin_guide.ditamap
docs/portal/developer-portal/uan_install_guide.ditamap

- Fixes CASMUSER-3189. This will also make CASMUSER-3188 easier.
Simplifies the structure of both UAN guides and changes both to better match the organization of the Hugo-generated docs.
N/A
Very low risk to tarball and HPESC publishing pipelines.

CASMUSER-3189

---

docs/portal/developer-portal/operations/Basic_UAN_Configuration.md
docs/portal/developer-portal/operations/Create_UAN_Boot_Images.md

This PR updates the UAN configuration overview to include the set/unset nologin layers in the UAN bootprep file.  Move the initial mention of using sat bootprep to the basic config page since that's what we want users to use.
Also removed some redundant info from the overview page.

Update bootprep and config overview

---

docs/portal/developer-portal/admin_publication.json
docs/portal/developer-portal/install_publication.json
vars.sh

- Fixes CASMUSER-3192
This does not need to go into this month's CSM recipe release. In fact, it **shouldn't** go into this release because I incremented the DOC_ID suffix variable for the next recipe release.
- Docs Tooling Pull Request
This change gives each release version of each UAN publication a unique "collection ID". HPESC views all docIDs that share the same collection ID as translations of the same document. 
This change allows us apply separate metadata to the UAN docs for a particular release. For example, publishing the UAN docs for an upcoming CSM recipe release as "confidential" (HPE viewable only) to HPESC when the official release day isn't known yet. 
See MTS-3267 for more details.
N/A
No known risk. The Hugo docs build process doesn't use this HPESC-specific metadata. …

adds incremented suffix to collection ID.

---

docs/portal/developer-portal/operations/Basic_UAN_Configuration.md

This PR adds some documentation around the CFS layers involved in basic UAN/Application Node configuration.  Without this information it is difficult for the sysadmin to know where to place any customizations to the overall node or image configuration.
- Fixes [CASMUSER-3210](https://jira-pro.it.hpe.com:8443/browse/CASMUSER-3210)

Add CFS layer details

---

docs/portal/developer-portal/hugo_toc.json
docs/portal/developer-portal/operations/csm_gpg_keys.md
docs/portal/developer-portal/operations/uan_ca_cert.md
docs/portal/developer-portal/operations/uan_gpg_keys.md
docs/portal/developer-portal/uan_admin_guide.ditamap
docs/portal/developer-portal/uan_install_guide.ditamap

This PR updates the documentation for the uan_gpg_keys and uan_ca_cert roles.  It also renames the file csm_gpg_keys.md to uan_gpg_keys.md to match the actual role name.
It resolves CASMUSER-3233.
After merging to main, this PR should be cherry-picked to release/uan-2.6.

CASMUSER-3233: Update docs for uan_gpg_keys and uan_ca_cert roles

---

docs/portal/developer-portal/advanced/Designating_Application_Nodes_for_K3s.md
docs/portal/developer-portal/advanced/Enabling_K3s.md
docs/portal/developer-portal/hugo_toc.json
docs/portal/developer-portal/uan_admin_guide.ditamap

This PR adds documentation on adding UAN nodes to the necessary HSM node groups to support K3s configuration.

Add information on setting up HSM Node Groups for K3s

---

docs/portal/developer-portal/advanced/Designating_Application_Nodes_for_K3s.md
docs/portal/developer-portal/advanced/Enabling_CAN_CHN.md
docs/portal/developer-portal/advanced/Enabling_K3s.md
docs/portal/developer-portal/advanced/Repurposing_Compute_as_UAN.md
docs/portal/developer-portal/advanced/SLES_Image.md
docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md
docs/portal/developer-portal/installation_prereqs/Configure_the_BIOS_of_an_HPE_UAN.md
docs/portal/developer-portal/installation_prereqs/Configure_the_BMC_for_UANs_with_iLO.md
docs/portal/developer-portal/installation_prereqs/Prepare_for_UAN_Product_Installation.md
docs/portal/developer-portal/operations/Basic_UAN_Configuration.md
docs/portal/developer-portal/operations/Boot_UANs.md
docs/portal/developer-portal/operations/Build_a_New_UAN_Image_Using_the_COS_Recipe.md
docs/portal/developer-portal/operations/CVE-2023-0461.md
docs/portal/developer-portal/operations/Configure_Interfaces_on_UANs.md
docs/portal/developer-portal/operations/Configure_Pluggable_Authentication_Modules_(PAM)_on_UANs.md
docs/portal/developer-portal/operations/Create_UAN_Boot_Images.md
docs/portal/developer-portal/operations/uan_disk_config.md
docs/portal/developer-portal/operations/uan_gpg_keys.md
docs/portal/developer-portal/operations/uan_hardening.md
docs/portal/developer-portal/operations/uan_interfaces.md
docs/portal/developer-portal/operations/uan_ldap.md
docs/portal/developer-portal/operations/uan_motd.md
docs/portal/developer-portal/operations/uan_packages.md
docs/portal/developer-portal/operations/uan_shadow.md
docs/portal/developer-portal/troubleshooting/Troubleshoot_UAN_Boot_Issues.md
docs/portal/developer-portal/troubleshooting/Troubleshoot_UAN_CFS_and_Network_Configuration_Issues.md
docs/portal/developer-portal/troubleshooting/Troubleshoot_UAN_Disk_Configuration_Issues.md
docs/portal/developer-portal/upgrade/Notable_Changes.md

Deduped HashiCorp vault steps, style fixes, consistently say that manual image steps are pre-IUF and pre-UAN 2.6.
- Relates to CASMUSER-3247
**Docs Pull Request**
- Lots of small wording changes suggested by our Acrolinx tool for spelling, grammar, readability, and other conformance to the HPE KM Style guide.
- More consistently state that the manual image creation steps (and related procedures) are only needed for pre-UAN 2.6 releases or if you are not using IUF for a 2.6+ release.
- The steps for setting the root password in the HashiCorp vault are now in one place instead of two.
N/A
Very low risk for breaking docs builds and performance because:
- this PR successfully builds
- no new files are added
- no files are deleted
- no new or strange Markdown syntax is added

CASMUSER-3247

---

release.sh

This adds the HPESC-specific JSON metadata files to ones covered by the variable substitution logic. Without this fix, `@product_version@` appears in the metadata and titles of the UAN guides on HPESC.
N/A
Very low risk.

added JSON metadata files to those covered by variables.

---

docs/portal/developer-portal/advanced/SLES_Image.md

A kernel parameter for booting UANs in GCP was in the docs for booting on a bare metal CSM system.
Fix the docs so ip=dhcp is documented by default.
- Fixes CASMUSER-3267

CASMUSER-3267: Fix kernel parameter for SLE booting

---

docs/portal/developer-portal/advanced/Designating_Application_Nodes_for_K3s.md
docs/portal/developer-portal/advanced/Enabling_K3s.md
docs/portal/developer-portal/build.sh
docs/portal/developer-portal/fop.xconf
docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md
docs/portal/developer-portal/installation_prereqs/Prepare_for_UAN_Product_Installation.md
docs/portal/developer-portal/operations/Basic_UAN_Configuration.md
docs/portal/developer-portal/operations/Build_a_New_UAN_Image_Using_the_COS_Recipe.md
docs/portal/developer-portal/operations/Create_UAN_Boot_Images.md
docs/portal/developer-portal/uan_install_guide.ditamap
docs/portal/developer-portal/upgrade/Notable_Changes.md

See description of TECHPUBS-4040 for details of fixes and rationale. **This is the fix for the main branch. I'll create another PR for the 2.7 release branch after this one merges**
The new `fop.xconf` is only used by Apache FOP as part of the PDF build process. The file in our docs repo overrides the file of the same name used by the default DITA-OT PDF transform.
The two K3s procedures now appear in both the Install and Admin Guides. I'm open to removing it from the Admin Guide if we decide setting up K3s should only be done during install or upgrade.
- Fixes TECHPUBS-4040
Fixes image sizing in PDF output and corrects some workflow issues.
N/A
For the PDF image sizing: the only new risk is if we decide to add more graphics and/or screenshots to the docs and 200 dpi …

fix image size in PDFs and workflow issues found in winter release install

---

docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md

This PR adds a link in the Install_the_UAN_Product_Stream.md file to the Enabling_K3s.md page for the admin to reference when UAIs on UANs is enabled. The prereqs in Enabling_K3s.md need to be performed before the IUF deploy-product stage is executed.
This PR must merge and a 2.7.3 tag placed on the release/uan-2.7 branch before the PR to main branch is merged.

add link to IUF instructions for K3s prereqs

---

docs/portal/developer-portal/upgrade/Notable_Changes.md
release_list.yml

This PR updates the doc versions to be built. UAN 2.7.3 is the latest version.
This PR must be merged after https://github.com/Cray-HPE/docs-uan/pull/62 is merged.  That PR will enable the creation of the tag 2.7.3 referenced in this PR.

Update release list for 2.7.3
