Cray-HPE/docs-uan

docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md
- Fixes [CASMUSER-3166](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3166)
Change reference to IUF docs to be URLs.
=> Update IUF references

docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md
This PR fixes some missed references to cos that should be uan or removed.  Also clarified the two COS layers that are needed.
=> Fix missed references

docs/portal/developer-portal/hugo_toc.json, docs/portal/developer-portal/operations/CVE-2023-0461.md, docs/portal/developer-portal/uan_admin_guide.ditamap
Create a mitigation guide for CVE-2023-0461. When the CVE is resolved by an official SUSE fix, this will be removed.
=> Add a CVE-2023-0461 mitigation guide

docs/portal/developer-portal/advanced/Enabling_K3s.md, docs/portal/developer-portal/hugo_toc.json, docs/portal/developer-portal/test-plan/K3s_Test_Plan.md, docs/portal/developer-portal/uan_admin.ditamap
=> K3s 2.5.10

docs/portal/developer-portal/hugo_toc.json
=> Fix capitalization issue

docs/portal/developer-portal/hugo_toc.json, docs/portal/developer-portal/operations/CVE_2023_0461.md, docs/portal/developer-portal/uan_admin.ditamap, docs/portal/developer-portal/uan_install.ditamap, docs/portal/developer-portal/upgrade/Notable_Changes.md
This PR add the CVE-2023-0461 mediation documentation to the UAN 2.5.8 documents.
NOTE: This PR needs to be verified on a system running UAN 2.5.8 before merging.
=> CVE-2023-0461 mediation for UAN 2.5.8

docs/portal/developer-portal/hugo_toc.json, docs/portal/developer-portal/operations/CVE_2023_0461.md, docs/portal/developer-portal/upgrade/Notable_Changes.md
This PR adds the CVE-2023-0461 mitigation procedure to UAN 2.5.10 documentation.
=> Add mitigation of CVE-2023-0461

docs/portal/developer-portal/uan_admin.ditamap, docs/portal/developer-portal/uan_install.ditamap
This PR updates the ditamap files for UAN 2.5.10
=> Update ditamap files for 2.5.10

docs/portal/developer-portal/operations/Configure_Interfaces_on_UANs.md
This PR adds prereqs for NMN bonding to the documentation in 2.5.10.
=> Add nmn bond prereqs to 2.5.10 docs

docs/portal/developer-portal/operations/Configure_Interfaces_on_UANs.md, docs/portal/developer-portal/operations/UAN_Ansible_Roles.md, docs/portal/developer-portal/uan_admin.ditamap, docs/portal/developer-portal/uan_install.ditamap
This PR updates the docs for 2.5.11 with CHN updates and and matches the format for all variables in UAN_Ansible_Roles.md to be the same.
=> Update docs for 2.5.11 (CHN update)

docs/portal/developer-portal/hugo_toc.json, docs/portal/developer-portal/operations/CVE_2023_0461.md, docs/portal/developer-portal/uan_admin.ditamap
Add in CVE mitigation missed in initial merge.
=> Add CVE-2023-0461 mitigation

docs/portal/developer-portal/operations/Configure_Interfaces_on_UANs.md, docs/portal/developer-portal/operations/UAN_Ansible_Roles.md
Add doc updates for CHN.  This appears in UAN 2.6.0-alpha.7.
=> Add uan_chn_device to main docs

docs/portal/developer-portal/advanced/Enabling_CAN_CHN.md, docs/portal/developer-portal/advanced/Enabling_K3s.md, docs/portal/developer-portal/advanced/Repurposing_Compute_as_UAN.md, docs/portal/developer-portal/advanced/SLES_Image.md, docs/portal/developer-portal/operations/Basic_UAN_Configuration.md, docs/portal/developer-portal/operations/Boot_UANs.md, docs/portal/developer-portal/operations/CVE-2023-0461.md, docs/portal/developer-portal/operations/Configure_Interfaces_on_UANs.md, docs/portal/developer-portal/operations/Configure_Pluggable_Authentication_Modules_(PAM)_on_UANs.md, docs/portal/developer-portal/operations/Create_UAN_Boot_Images.md, docs/portal/developer-portal/operations/uan_disk_config.md, docs/portal/developer-portal/operations/uan_interfaces.md, docs/portal/developer-portal/operations/uan_ldap.md, docs/portal/developer-portal/operations/uan_packages.md, docs/portal/developer-portal/upgrade/Notable_Changes.md
Fixes STP-3678
Docs Pull Request
Fixes a bunch of typos found by Sarah and listed in STP-3678.
- [] I tested this on internal system (x)
N/A
Very low risk. This PR contains just a bunch of small docs corrections.
=> fixes listed in STP-3678

docs/portal/developer-portal/advanced/Enabling_K3s.md, docs/portal/developer-portal/installation_prereqs/Prepare_for_UAN_Product_Installation.md
Document the ability to get K3s MetalLB IPs from SLS.
=> casmuser-3199: Add info for K3s MetalLB pool

docs/portal/developer-portal/operations/Create_UAN_Boot_Images.md
CASMUSER-3245
Restructuring & rewording to make one area of the docs easier to follow.
- [] I tested this on internal system (x) (if yes, please include results or a description of the test)
No test builds done because this a low-risk docs restructuring PR.
N/A
Low risk
=> restructured Create_UAN_Boot_Images.md to be easier to follow

.github/workflows/backport.yaml, docs/hugo/docs-uan/themes/hugo-theme-learn/layouts/partials/menu-footer.html, release_list.yml, templates/config.toml.j2
* remove default footer
* reorder doc list
* disable checkmark for visited links
=> Misc fixes

docs/portal/developer-portal/advanced/Enabling_K3s.md
- Fixes # Update KUBECONFIG value
- Docs Pull Request : https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6515
Update the KUBECONFIG value in example given.
- [] I have included documentation in my PR (or it is not required)
- [] I tested this on internal system (x) (if yes, please include results or a description of the test)
=> Update Enabling_K3s.md kubeconfig value

docs/portal/developer-portal/advanced/Designating_Application_Nodes_for_K3s.md, docs/portal/developer-portal/advanced/Enabling_K3s.md, docs/portal/developer-portal/build.sh, docs/portal/developer-portal/fop.xconf, docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md, docs/portal/developer-portal/installation_prereqs/Prepare_for_UAN_Product_Installation.md, docs/portal/developer-portal/operations/Basic_UAN_Configuration.md, docs/portal/developer-portal/uan_install_guide.ditamap
- Fixes TECHPUBS-4040 but for the UAN 2.7 branch
See #60 for full details.
N/A
Same small risks as #60
=> Techpubs 4040 2.7

docs/portal/developer-portal/advanced/Enabling_K3s.md, docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md, docs/portal/developer-portal/operations/Build_a_New_UAN_Image_Using_the_COS_Recipe.md, docs/portal/developer-portal/operations/Create_UAN_Boot_Images.md, docs/portal/developer-portal/upgrade/Notable_Changes.md
This PR addresses documentation issues in UAN 2.7.1 described in CASMUSER-3293.
=> Casmuser 3293 docs updates for UAN 2.7.1

docs/portal/developer-portal/advanced/Enabling_K3s.md, docs/portal/developer-portal/operations/Build_a_New_UAN_Image_Using_the_COS_Recipe.md, docs/portal/developer-portal/operations/Create_UAN_Boot_Images.md, docs/portal/developer-portal/upgrade/Notable_Changes.md
PR for documentation changes addressing CASMUSER-3293 for UAN 2.7.3.
=> Casmuser 3293 2.7.3

docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md
This PR updates the information around RPM repos provided by UAN.
CASMUSER-3290
=> Update rpm repo info

docs/portal/developer-portal/build.sh, docs/portal/developer-portal/fop.xconf
- Fixes CASMUSER-3294 for 2.7.1
- [] I tested this on internal system (x) **N/A since this is very low risk and has already been tested in main and UAN 2.7.3**
N/A
Very low risk
=> Casmuser 3294

docs/portal/developer-portal/operations/Basic_UAN_Configuration.md
- Fixes Casmuser-3291
This is the 2.7.3 version of this [PR for 2.7.1](https://github.com/Cray-HPE/docs-uan/pull/68/files#)
- [] I tested this on internal system: N/A
N/A
Very low risk. No linking or structure changes are involved. Only content within one file.
=> Casmuser-3291 for 2.7.3

docs/portal/developer-portal/install/Install_the_UAN_Product_Stream.md, docs/portal/developer-portal/operations/Basic_UAN_Configuration.md
- Fixes CASMUSER-3300
- [] I tested this on internal system. **N/A since this only adds one para to two existing files**
N/A
Very low risk. This change only adds one bolded paragraph to two Markdown files so that both UAN guides notifies users about the merge with USS.
=> added disclaimers to both UAN guides about merge with USS
